### ISSUE TITLE
20Mb attachment causing "Application failed to respond" with link to railway.com in error response

### ISSUE THREAD

**Issue by joe-mohan** [resendlabs/resend-node#115] opened 2023-06-21 12:05 UTC
When trying to send an email via node with the attached file. 

[Free_Test_Data_10.5MB_PDF.pdf](https://github.com/resendlabs/resend-node/files/11817283/Free_Test_Data_10.5MB_PDF.pdf)

It causes a strange error that returns a html page for railway.app. It's under the 40Mb limit. Any ideas what's happening here? Emails send fine with this pdf: 

[dummy.pdf](https://github.com/resendlabs/resend-node/files/11817322/dummy.pdf)

**Comment by marianobenitezz** [comment] 2023-06-21 16:00
Having the same error here. When i add `filesToSend` to the `attachments` to send the email, it responds with the Railway 503/404 error page

      const filesToSend = await Promise.all(files.map(async (file: Blob) => {
        
        const arrayBuffer = await file.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);

        return { filename: file.name, content: buffer };
      }));

**Comment by bukinoshita** [comment] 2023-06-21 19:07
Does the same error show up when using `path` instead?

**Comment by marianobenitezz** [comment] 2023-06-22 12:08
@bukinoshita I'm sending the files from a form to a Next.js 13 route (app dir) in a formData, they are not files in the filesystem. It started to fail suddenly yesterday. I could send emails with the files an hour before it stopped working.

The html is the Railway error page

      <h1 class="error-404">Nothing here... yet</h1>
      <h1 class="error-503">Application failed to respond</h1>
      <a href="https://railway.app" target="_blank"> Go to Railway </a>

**Comment by bukinoshita** [comment] 2023-06-29 04:03
@marianobenitezz got it. We did some improvements to handle larger payload sizes, but we will keep investigating this issue. If you have an example file that you're sending for us to run in our tests would be helpful.

**Comment by marianobenitezz** [comment] 2023-06-29 16:18
@bukinoshita I was about to make a separate reproduction repo but, since it seems to be working now, I can open source the project directly.

• Repo: https://github.com/marianobenitezz/iconika

**Comment by marianobenitezz** [comment] 2023-06-29 16:24
@bukinoshita I was about to make a separate reproduction repo but, since it seems to be working now, you can close this if you prefer.

A workaround if this happens is upload the files to a cloud provider and pass the url to the `path` key.

If you still want to check it out, I can open source the project directly.

• Repo: https://github.com/marianobenitezz/iconika
• Route: /inscribirme
• Online at: https://iconika.vercel.app (soon domain will change to iconika.com.ar)

**Closed** 2023-07-11 15:34 UTC
